CREATE TABLE IF NOT EXISTS results (
    ResultID INTEGER PRIMARY KEY AUTOINCREMENT,
    UserID INTEGER NOT NULL,
    RoverName TEXT NOT NULL,
    WaterChance REAL NOT NULL,
    TimeLimit INTEGER NOT NULL,
    TerrainDiscovered TEXT NOT NULL
);
